### ISSUE TITLE
Xcode build error on release: "library not found for -lRNNodeJsMobile"

### ISSUE THREAD

**Issue by Benetzz** [janeasystems/nodejs-mobile#42]
* **Version**: "^0.1.3",
* **Platform**: Mac Os
* **Subsystem**: React Native, iOS, Xcode

Hi there, 

thank you for this useful library. 

I have a problem in my app on release mode on iOS. When on Xcode, the target schema is on debug all work good, but when i try to run it on release mode the build fail with error: "library not found for -lRNNodeJsMobile". What can be the problem? What should i look for?

Thank you all

**Comment by jaimecbernardo** [comment]
Hi @Benetzz , Thank you for the issue and the kind comments.

From the name in the error, I'm assuming you are referring to the `nodejs-mobile-react-native` plugin.

The error you are getting is caused by the Release mode building all architectures by default (`Build Settings / Build Active Architecture Only` ). `nodejs-mobile` provides binaries for `arm64` only, as the target support is for iOS version `>= 11.0` so the build will fail due to being unable to find the `armv7` binaries. The `RNNodeJsMobile.xcodeproj` has a deployment target of `11.0` but React Native applications are normally pre-configured by the client on a lower target.

You may get around this in three different ways:
- Setting the Deployment Target to `11.0` in `Build Settings / Deployment / iOS Deployment Target`. **(Recommended)**
- Changing `Build Active Architecture Only` only to `Yes` in `Build Settings / Architectures / Build Active Architectures Only / Release`. **(Not Recommended)**
- Removing `armv7` and `armv7s` from `Build Settings / Architectures / Valid Architectures / Release`. **(Not Recommended)**

I hope this was helpful.
Please let us know if this solved your issue.

**Comment by Benetzz** [comment]
I've fixed. The problem was the folder frameworks duplicated by the react-native-link, and the project was in an inconsistent state.

**Comment by jaimecbernardo** [comment]
Thank you!
I was able to replicate the error without duplicated Frameworks folders, but it's good to know that also causes the error, so we can look into it.
Glad to know the issue was solved for your case.

**Comment by saurabhsahu13** [comment]
Thanks @jaimecbernardo for the answer and the awesome library. It was very helpful.

**Comment by kilianc** [comment]
I still get this error today in `Xcode 10` `react-native@0.57.6` and `nodejs-mobile-react-native@0.3.2`

```
Libtool /Users/foo/Library/Developer/Xcode/DerivedData/AppName-ehapiqxqgnqeeafulnbrftgeibpy/Build/Products/Release-iphonesimulator/libRNNodeJsMobile.a normal x86_64 (in target: RNNodeJsMobile)
    cd /Volumes/WS/workspace/AppName/node_modules/nodejs-mobile-react-native/ios
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -L/Users/foo/Library/Developer/Xcode/DerivedData/AppName-ehapiqxqgnqeeafulnbrftgeibpy/Build/Products/Release-iphonesimulator -filelist /Users/foo/Library/Developer/Xcode/DerivedData/AppName-ehapiqxqgnqeeafulnbrftgeibpy/Build/Intermediates.noindex/RNNodeJsMobile.build/Release-iphonesimulator/RNNodeJsMobile.build/Objects-normal/x86_64/RNNodeJsMobile.LinkFileList -lRNNodeJsMobile -o /Users/foo/Library/Developer/Xcode/DerivedData/AppName-ehapiqxqgnqeeafulnbrftgeibpy/Build/Products/Release-iphonesimulator/libRNNodeJsMobile.a

error: Build input file cannot be found: '/Volumes/WS/workspace/AppName/ios/libRNNodeJsMobile.a'
```

**Comment by jaimecbernardo** [comment]
Hi @kilianc ,
I've been unable to replicate your issue with the versions you've indicated.
Do you have some specific instructions or a replication repo?

**Comment by kilianc** [comment]
@jaimecbernardo are you building for `release`? It works in dev/debug but not in release

**Comment by jaimecbernardo** [comment]
Hi @kilianc ,
`nodejs-mobile` only supports 64bit architectures, it's possible that XCode is trying to build 32-bit binaries. Please try to change the Deployment Target of your App to `11.0` (where 32bit support was dropped) to verify if that's the source of the problem.

**Comment by kilianc** [comment]
Hey @jaimecbernardo, thanks for the response. I am targeting `12.1` while I get the error

**Comment by jaimecbernardo** [comment]
Hi @kilianc , Your log output had this line:
```
export IPHONEOS_DEPLOYMENT_TARGET=9.0
```
That's why I thought the error could be related to that. Do you have updated logs/ a replication repo for your current issue, then?

**Comment by thhmoc67** [comment]
Thank you very much @jaimecbernardo 
it Worked 💯 👍
