### ISSUE TITLE
Print errors from stderr to Java side [android]

### ISSUE THREAD

**Issue by staltz** [janeasystems/nodejs-mobile#6]
Take the sample project from https://github.com/janeasystems/nodejs-mobile-samples, `SuspendResume` for React Native, and modify `nodejs-assets/nodejs-project/main.js`:

```diff
// ...
rn_bridge.channel.on('message', (msg) => {
  switch(msg) {
    case 'versions':
      msg_number++;
+     throw new Error('this should show in Android logcat');
      rn_bridge.channel.send(
        "This is message number " +
        msg_number +
        ". Versions: " +
        JSON.stringify(process.versions)
      );
  break;
  // ...
```

This will crash the node.js background project, but it'll happen silently, making it difficult to debug why. Probably errors to stderr should show in Android's log(cat).

**Comment by jaimecbernardo** [comment]
Hi @staltz ,

Thanks for your issue.
For the time being, a workaround is trying to catch all errors in the bridge callback and sending them out to the react-native side to show them through your app-defined protocol.

This is a known issue. A possible way to solve this is by having an initialization step to redirect stdout and stderr to logcat by default. A PR or discussion would be welcome, if you've already had to deal with a similar problem.

**Comment by staltz** [comment]
The workaround might work for now, thanks for the hint.

Question: does this spawn a new process? Or does it just "run node" in the current process? https://github.com/janeasystems/nodejs-mobile-react-native/blob/1a5cf5e3c8d11a92eb88726dbb301a15dc30efa4/android/src/main/cpp/native-lib.cpp#L25

**Comment by jaimecbernardo** [comment]
It runs node in the current process, but in its own thread, started here: https://github.com/janeasystems/nodejs-mobile-react-native/blob/1a5cf5e3c8d11a92eb88726dbb301a15dc30efa4/android/src/main/java/com/janeasystems/rn_nodejs_mobile/RNNodeJsMobileModule.java#L85

**Comment by staltz** [comment]
I just tested nodejs-mobile-react-native v0.1.2 and this issue is resolved there. Thanks.

**Comment by jfr3000** [comment]
I'm using 0.3.0 and I am still having this issue. I'm using `react-native log-android` - should I be using something else?

**Comment by jaimecbernardo** [comment]
Hi @jfr3000 , `react-native log-android` should only work for react-native log messages.

You can see the node's runtime output in `adb logcat`.
This is one of the possible ways to see it:
`adb logcat | grep "NODEJS-MOBILE"`

**Comment by jfr3000** [comment]
Ah, my mistake, thanks! This might me a helpful addition to the Getting Started Guide.
